// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_Kizy.Models;

namespace Mission06_Kizy.Migrations
{
    [DbContext(typeof(MovieApplicationContext))]
    partial class MovieApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_Kizy.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            Category = "Action / Adventure",
                            Director = "Joss Whedon",
                            Edited = false,
                            LentTo = " ",
                            Notes = " ",
                            Rating = "PG-13",
                            Title = "Avengers, The",
                            Year = 2012
                        },
                        new
                        {
                            ApplicationId = 2,
                            Category = "Action / Adventure",
                            Director = "Joel Schumacher",
                            Edited = false,
                            LentTo = " ",
                            Notes = " ",
                            Rating = "PG-13",
                            Title = "Batman & Robin",
                            Year = 1997
                        },
                        new
                        {
                            ApplicationId = 3,
                            Category = "Action / Adventure",
                            Director = "Christopher Nolan",
                            Edited = true,
                            LentTo = " ",
                            Notes = " ",
                            Rating = "PG-13",
                            Title = "Batman Begins",
                            Year = 2005
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
